version: '3.7'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql

  web:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/myapp
    command: bundle exec rails server -b 0.0.0.0

  elasticsearch:
    build: ./docker/elasticsearch
    container_name: elasticsearch_1
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.16.2
  #   environment:
  #     SERVER_NAME: localhost:5601
  #     ELASTICSEARCH_URL: http://es_sample:9200
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     - es
